sudo: required
dist: trusty
addons:
  chrome: stable
  firefox: latest
language: node_js
node_js:
- '8'
cache:
  yarn: true
branches:
  except:
  - stable
before_install:
- export START_TIME=$( date +%s )
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm i -g yarn
install:
- yarn add @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_success:
- ckeditor5-dev-tests-save-revision
after_script:
- export END_TIME=$( date +%s )
- ckeditor5-dev-tests-notify-travis-status
env:
  global:
  - secure: MrzUiFehTAF5C+LWnJY1qP3KA4kGprSo43ot9l/CM/40YTAVlEetXEOd7Xkk+m4lVr6fxdh7zoSrJPpDiS0DuuiKDsQanZkO2IMlV0Sg32MTtufAfjAD5yNk1aESxs6DNcOGANdVYebK7PN0iCstSSaqZGhtsv5zosmyFyNWaZjeacGmfItyDo88J2ZyX1mG5db/KboHK1+rn7IaT1y7vDlQ8oW4BWjD/KsCp25UiP92RBT/vxvh9XdzZ65uBrIE/LhbSm9RXL/rc5WGXkslcS+chjzJ+K3zuZ4sjxM8MmnRm8cJAWxM8WcFM2W2YSs95G5lSeYHSg3/XZNtcNCN0dcsE9pB4UPHEqTAV5ZPakUYhBC2g8kVEnfOotn+Dgnl0TBzRomk7kmaJ2f4RPXrk+uk4xgdo8AnSt1QEwDljAZduJqIpm376tS9Ltl71NVxyDM0HHwLwKV8kUWNbRkGJXZFc0dNPIhzoVaJ3qnJNLV8QQbGLhCMJ70u7rTwySiaavHJgYNGDECqBhLeJOoaeQE4WAOoz7HZo4sXUHoqr6yLHv5W3NdI9q0S2F6bEJrrog/L12Vb+pIOd7Ru+FPdqWemUDpizHLdz6uHGG9IfRlzwfwClaoZJCidIL2hAdY5tPTyPQjcoJXRIrHaVuNx3BvEjH5otkTVrNPIe455j5w=
  - secure: jlUQ4UgF8ihkyPOeG8e1FOdxltYRH8+/qY4GOewtYawCaffS4U0mvfluLe2BwvmRzzwI485e5Zimxvw372355+7ygK21GcK4GDrVcsIxdwuw+49Pi4G1vdo192/A1Ryy/CoHO/6e1bNJ46EYqvCLy0RAudMKmM75sBIPN9ViohnpkiHasMzbOiD9LbQFLFP8DNb8hOK6tPDQf6NG4Z/16sRURrzif4raBaZ2qU/r00wKz0D7XAOBIO5rfsBM8+hXGced0XzSNnA5CYn+U9wO7XJdGm6aLJti98bZkeVmc9CiV520G/kvMEuDWxPAsCuvun3nIt7TyIUrnLFNJwoH+nno+p2EMysWDBaYgpfDp/7zM2tHz2pzcrVNdFjZ9NYx9Jby8F9L+KrhTw+Z0Z1kD2xGFvP8YgKEb0x/nWCanvaQvS9yW6lFE43oJ7gGjsdXKiYF0tlUDSprizOc7oRTtGan8LCUNfPI8PalWmxHDh+wsphCLmhw5IarYsWqLiBAP2p3vYrGn5JRuHNfMkw8rfmRXT5bds3g/87F5j4uAeaRgXH0/YMEF40vKIw5yEijZO/mVosLtf9RlImE8WFmJ/ias5bCIRzIjHmvef3QsehiiULDvm3Kr4mGITMpLrn3jvXjG1a3oVLnpOqsidbDIYD2DytFZ7BZi2F8DtVJ2mQ=
  - secure: ZsQ5TZII5NT5nXkN3Cq26iD55wvrYKFt8apHX++dS/SRRB4Eze5e4YFFXTXJlVPRo1epoXCIM5jxSZ1xNaNCIgcBscmbYfEJ+BiqQJn59zl+xZwNkg3w4OcwhBH+ZrfzuOJCwNFS1g5FTjGgUBQ7BrffWgRw0JrZA1aYqmtlyV3wQFb49+UiXFYkowqshafJ5kGBmch6JZxdQYKbIS/AkAMdwxckXXsQ50FHDwQVoddmzUR1ltiE89CntXfJUyp1x7tR97u9gwwn+eLlC51rMwyqqzdVAvIvxUA85MlKDIKeNVIlglrerEN/xVBGDb6r/Z2gnypZfXWxhc6dn1FWuDCC/1zuq9B7Kbv1YhUTXS9iGtKIEZMjBKVwgLR4kza4ictDp43PK8QjrfLNDeOhlB8BVcCzVcatL3vxRcsXwEd60RFfoYPy6vatUUDJ98Kb0MOiandRa2rRuy47RGtg/LsKv51jpvyv3BdTOS5YvAuZxze8kDqsJwI51Y3txAWNkZMoGYoY6vXexXV3wMKXM9rYlYTjTjc5SQKrQnRw4pGbTPxckFTiM4xNWkUmPvmxeWYCj792i+jQapLC4AVLYK3IeeG+LDuvvdEXdgE5xKNOy42kI0cs10wvWjOMKf8v0Oe57ax+qC7WWjasAzkkainH2XcB1urkUxsvq4VB1l0=
